### ISSUE TITLE
모바일 반응형 멘트 수정 

### ISSUE THREAD

**Issue by Eight-Corner** [Eight-Corner/CampFire#12]
![image](https://user-images.githubusercontent.com/68332735/119963480-1d994f00-bfe3-11eb-9e54-fda07ed601ea.png)

610px 까지 모닥불 멘트 정렬 못생김 문제 
(폰트 사이즈 줄여서 해결 부탁드림다~)

**Comment by Heekng** [comment]
모닥불멘트 완료!
